#!/usr/bin/env python3
"""
Generate Ornstein--Uhlenbeck forecasting data with a continuous/discrete interpolation.

Construction:
- Latent trajectory x_t generated by Euler--Maruyama
- Continuous observation: cont_t = [x_t] @ W_cont  in R^16
- Discrete observation:
    * For each trajectory independently, compute x_min/x_max
    * Bin x into 16 bins: symbol_t in {0,...,15}
    * Map each symbol to one column of a global random orthogonal 16x16 matrix Q
- Mixed observation:
    obs_t = (1 - eta) * cont_t + eta * disc_t
- Input: first L steps of obs, shape (L, 16)
- Target: next horizon steps of obs, shape (horizon, 16)

Saved NPZ keys:
    x_train, y_train, x_val, y_val, x_test, y_test, W_cont, codebook, meta_json

Note:
- Unlike VDP/DHO/FD, OU has a 1D latent state. To keep the same 16D mixed-observation
  format, we use a 1D continuous map and 16-bin per-trajectory discretization.
"""

import argparse
import json
from pathlib import Path

import numpy as np

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None


def progress(it, **kwargs):
    return tqdm(it, **kwargs) if tqdm is not None else it

def ou_step(x: float, theta: float, sigma: float, dt: float, rng: np.random.Generator):
    eps = rng.normal(0.0, 1.0)
    return x + (-theta * x) * dt + sigma * np.sqrt(dt) * eps


def sample_x0(rng: np.random.Generator, theta: float, sigma: float, mode: str, x0_range):
    if mode == "zero":
        return 0.0
    if mode == "uniform":
        return float(rng.uniform(x0_range[0], x0_range[1]))
    if mode == "stationary":
        var = (sigma * sigma) / (2.0 * theta)
        return float(rng.normal(0.0, np.sqrt(var)))
    raise ValueError(f"Unknown x0_mode: {mode}")


def simulate_ou(theta: float, sigma: float, total_len: int, dt: float, x0: float, burn_in: int = 0, rng=None):
    rng = np.random.default_rng() if rng is None else rng
    x = float(x0)

    for _ in range(int(burn_in)):
        x = ou_step(x, theta, sigma, dt, rng)

    xs = np.empty(total_len, dtype=np.float32)
    for t in range(total_len):
        x = ou_step(x, theta, sigma, dt, rng)
        xs[t] = x

    return xs

def build_continuous_map(d_input: int, seed: int = 123):
    rng = np.random.default_rng(seed)
    W = rng.normal(size=(1, d_input)).astype(np.float32)
    W /= (np.linalg.norm(W, axis=0, keepdims=True) + 1e-12)
    return W


def build_orthogonal_codebook(d_input: int, seed: int = 37):
    if d_input != 16:
        raise ValueError(f"This script assumes d_input=16 so there are 16 bins; got d_input={d_input}")
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(d_input, d_input))
    Q, _ = np.linalg.qr(A)
    return Q.astype(np.float32)

def quantize_per_trajectory(xs: np.ndarray) -> np.ndarray:
    x_min, x_max = float(xs.min()), float(xs.max())
    if x_max <= x_min:
        x_max = x_min + 1e-6

    x_norm = (xs - x_min) / (x_max - x_min + 1e-12)
    x_bin = np.floor(16.0 * x_norm).astype(np.int64)
    x_bin = np.clip(x_bin, 0, 15)
    return x_bin.astype(np.int64)


def continuous_observation(xs: np.ndarray, W_cont: np.ndarray) -> np.ndarray:
    z = xs[:, None].astype(np.float32)
    return z @ W_cont


def discrete_observation(symbols: np.ndarray, codebook: np.ndarray) -> np.ndarray:
    return codebook[:, symbols].T.astype(np.float32)


def build_observation(xs: np.ndarray, eta: float, W_cont: np.ndarray, codebook: np.ndarray):
    symbols = quantize_per_trajectory(xs)
    cont = continuous_observation(xs, W_cont)
    disc = discrete_observation(symbols, codebook)
    obs = (1.0 - eta) * cont + eta * disc
    return obs.astype(np.float32), symbols


def simulate_one_example(
    theta: float,
    sigma: float,
    L: int,
    horizon: int,
    dt: float,
    x0: float,
    eta: float,
    W_cont: np.ndarray,
    codebook: np.ndarray,
    burn_in: int = 0,
    rng=None,
):
    total_len = L + horizon
    xs = simulate_ou(theta=theta, sigma=sigma, total_len=total_len, dt=dt, x0=x0, burn_in=burn_in, rng=rng)
    obs, symbols = build_observation(xs, eta=eta, W_cont=W_cont, codebook=codebook)

    x_in = obs[:L]
    y_out = obs[L:L + horizon]
    return x_in, y_out, symbols


def make_split(
    n: int,
    split_name: str,
    L: int,
    horizon: int,
    dt: float,
    eta: float,
    theta_min: float,
    theta_max: float,
    sigma_min: float,
    sigma_max: float,
    x0_mode: str,
    x0_range,
    burn_in: int,
    seed: int,
    W_cont: np.ndarray,
    codebook: np.ndarray,
):
    rng = np.random.default_rng(seed)

    thetas = rng.uniform(theta_min, theta_max, size=n).astype(np.float32)
    sigmas = rng.uniform(sigma_min, sigma_max, size=n).astype(np.float32)

    X = np.empty((n, L, 16), dtype=np.float32)
    Y = np.empty((n, horizon, 16), dtype=np.float32)

    unique_symbol_counts = []

    for i in progress(range(n), total=n, desc=f"Generating {split_name}", unit="traj"):
        x0 = sample_x0(rng, theta=float(thetas[i]), sigma=float(sigmas[i]), mode=x0_mode, x0_range=x0_range)
        x_in, y_out, symbols = simulate_one_example(
            theta=float(thetas[i]),
            sigma=float(sigmas[i]),
            L=L,
            horizon=horizon,
            dt=dt,
            x0=float(x0),
            eta=float(eta),
            W_cont=W_cont,
            codebook=codebook,
            burn_in=burn_in,
            rng=rng,
        )

        X[i] = x_in
        Y[i] = y_out
        unique_symbol_counts.append(int(np.unique(symbols[:L]).size))

        if i < 3:
            print(f"[{split_name} sample {i}] unique symbols in input = {np.unique(symbols[:L]).size}")
            print(f"[{split_name} sample {i}] first 24 symbols = {symbols[::24].tolist()}")
            print(f"[{split_name} sample {i}] unique 16D vectors in input = {np.unique(x_in, axis=0).shape[0]}")

    stats = {
        "avg_unique_symbols": float(np.mean(unique_symbol_counts)),
        "min_unique_symbols": int(np.min(unique_symbol_counts)),
        "max_unique_symbols": int(np.max(unique_symbol_counts)),
    }

    if horizon == 1:
        Y = Y[:, 0, :]

    return X, Y, stats


def main():
    p = argparse.ArgumentParser()

    p.add_argument("--out", type=str, required=True)

    p.add_argument("--L", type=int, default=1024)
    p.add_argument("--horizon", type=int, default=16)
    p.add_argument("--delta", type=float, default=0.01)
    p.add_argument("--eta", type=float, default=1.0)

    p.add_argument("--d_input", type=int, default=16)

    p.add_argument("--n_train", type=int, default=20000)
    p.add_argument("--n_val", type=int, default=2000)
    p.add_argument("--n_test", type=int, default=2000)

    p.add_argument("--theta_min", type=float, default=0.2)
    p.add_argument("--theta_max", type=float, default=2.0)
    p.add_argument("--sigma_min", type=float, default=0.1)
    p.add_argument("--sigma_max", type=float, default=1.0)

    p.add_argument("--x0_mode", type=str, default="stationary", choices=["zero", "uniform", "stationary"])
    p.add_argument("--x0_range", type=float, nargs=2, default=(-1.0, 1.0))

    p.add_argument("--burn_in", type=int, default=0)

    p.add_argument("--seed", type=int, default=37)
    args = p.parse_args()

    if args.d_input != 16:
        raise ValueError("This script is written for d_input=16 exactly.")
    if not (0.0 <= args.eta <= 1.0):
        raise ValueError("--eta must lie in [0, 1].")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    W_cont = build_continuous_map(d_input=args.d_input, seed=args.seed + 101)
    codebook = build_orthogonal_codebook(d_input=args.d_input, seed=args.seed + 202)

    x_train, y_train, train_stats = make_split(
        n=args.n_train,
        split_name="train",
        L=args.L,
        horizon=args.horizon,
        dt=args.delta,
        eta=args.eta,
        theta_min=args.theta_min,
        theta_max=args.theta_max,
        sigma_min=args.sigma_min,
        sigma_max=args.sigma_max,
        x0_mode=args.x0_mode,
        x0_range=args.x0_range,
        burn_in=args.burn_in,
        seed=args.seed + 0,
        W_cont=W_cont,
        codebook=codebook,
    )

    x_val, y_val, val_stats = make_split(
        n=args.n_val,
        split_name="val",
        L=args.L,
        horizon=args.horizon,
        dt=args.delta,
        eta=args.eta,
        theta_min=args.theta_min,
        theta_max=args.theta_max,
        sigma_min=args.sigma_min,
        sigma_max=args.sigma_max,
        x0_mode=args.x0_mode,
        x0_range=args.x0_range,
        burn_in=args.burn_in,
        seed=args.seed + 1,
        W_cont=W_cont,
        codebook=codebook,
    )

    x_test, y_test, test_stats = make_split(
        n=args.n_test,
        split_name="test",
        L=args.L,
        horizon=args.horizon,
        dt=args.delta,
        eta=args.eta,
        theta_min=args.theta_min,
        theta_max=args.theta_max,
        sigma_min=args.sigma_min,
        sigma_max=args.sigma_max,
        x0_mode=args.x0_mode,
        x0_range=args.x0_range,
        burn_in=args.burn_in,
        seed=args.seed + 2,
        W_cont=W_cont,
        codebook=codebook,
    )

    meta = {
        "system": "ornstein_uhlenbeck",
        "task": "forecast_future_mixed_observation",
        "discretization": "euler_maruyama",
        "L": int(args.L),
        "horizon": int(args.horizon),
        "delta": float(args.delta),
        "eta": float(args.eta),
        "d_input": int(args.d_input),
        "theta_min": float(args.theta_min),
        "theta_max": float(args.theta_max),
        "sigma_min": float(args.sigma_min),
        "sigma_max": float(args.sigma_max),
        "x0_mode": str(args.x0_mode),
        "x0_range": [float(args.x0_range[0]), float(args.x0_range[1])],
        "burn_in": int(args.burn_in),
        "binning": "per_trajectory_16_bins_on_[xmin,xmax]",
        "codebook": "global_random_orthogonal_16x16_columns",
        "train_symbol_stats": train_stats,
        "val_symbol_stats": val_stats,
        "test_symbol_stats": test_stats,
        "seed": int(args.seed),
    }

    np.savez_compressed(
        out_path,
        x_train=x_train,
        y_train=y_train,
        x_val=x_val,
        y_val=y_val,
        x_test=x_test,
        y_test=y_test,
        W_cont=W_cont,
        codebook=codebook,
        meta_json=json.dumps(meta),
    )

    print(f"Saved: {out_path}")
    print(f"x_train {x_train.shape}, y_train {y_train.shape}")
    print(f"train avg unique symbols: {train_stats['avg_unique_symbols']:.2f}")
    print(f"train min/max unique symbols: {train_stats['min_unique_symbols']} / {train_stats['max_unique_symbols']}")


if __name__ == "__main__":
    main()
