#!/usr/bin/env python3
"""
Generate Van der Pol forecasting data with a continuous/discrete interpolation.

Construction:
- Latent trajectory z_t = (x_t, v_t) generated by RK4
- Continuous observation: cont_t = [x_t, v_t] @ W_cont  in R^16
- Discrete observation:
    * For each trajectory independently, compute x_min/x_max/v_min/v_max
    * Bin x and v each into 4 bins
    * 16 total bins: symbol_t = 4 * x_bin_t + v_bin_t
    * Map each symbol to one column of a global random orthogonal 16x16 matrix Q
- Mixed observation:
    obs_t = (1 - eta) * cont_t + eta * disc_t
- Input: first L steps of obs, shape (L, 16)
- Target: next horizon steps of obs, shape (horizon, 16)

Saved NPZ keys:
    x_train, y_train, x_val, y_val, x_test, y_test, W_cont, codebook, meta_json
"""

import argparse
import json
from pathlib import Path

import numpy as np

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None


def progress(it, **kwargs):
    return tqdm(it, **kwargs) if tqdm is not None else it

def vdp_rhs(x: float, v: float, mu: float):
    dx = v
    dv = mu * (1.0 - x * x) * v - x
    return dx, dv


def rk4_step(x: float, v: float, mu: float, dt: float):
    k1x, k1v = vdp_rhs(x, v, mu)
    k2x, k2v = vdp_rhs(x + 0.5 * dt * k1x, v + 0.5 * dt * k1v, mu)
    k3x, k3v = vdp_rhs(x + 0.5 * dt * k2x, v + 0.5 * dt * k2v, mu)
    k4x, k4v = vdp_rhs(x + dt * k3x, v + dt * k3v, mu)

    x_next = x + (dt / 6.0) * (k1x + 2.0 * k2x + 2.0 * k3x + k4x)
    v_next = v + (dt / 6.0) * (k1v + 2.0 * k2v + 2.0 * k3v + k4v)
    return x_next, v_next


def simulate_vdp(mu: float, total_len: int, dt: float, x0: float, v0: float, burn_in: int = 0):
    x = float(x0)
    v = float(v0)

    for _ in range(int(burn_in)):
        x, v = rk4_step(x, v, mu, dt)

    xs = np.empty(total_len, dtype=np.float32)
    vs = np.empty(total_len, dtype=np.float32)

    for t in range(total_len):
        x, v = rk4_step(x, v, mu, dt)
        xs[t] = x
        vs[t] = v

    return xs, vs

def build_continuous_map(d_input: int, seed: int = 123):
    """
    Returns W_cont of shape (2, d_input).
    """
    rng = np.random.default_rng(seed)
    W = rng.normal(size=(2, d_input)).astype(np.float32)
    # Normalize columns for stable scale
    W /= (np.linalg.norm(W, axis=0, keepdims=True) + 1e-12)
    return W


def build_orthogonal_codebook(d_input: int, seed: int = 37):
    """
    Returns Q of shape (d_input, d_input), orthogonal.
    Columns are the code vectors.
    """
    if d_input != 16:
        raise ValueError(f"This script assumes d_input=16 so there are 16 bins; got d_input={d_input}")
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(d_input, d_input))
    Q, _ = np.linalg.qr(A)
    return Q.astype(np.float32)


def quantize_per_trajectory(xs: np.ndarray, vs: np.ndarray) -> np.ndarray:
    """
    xs, vs: shape (T,)
    Returns symbol indices in {0,...,15}, shape (T,).

    Binning is per-trajectory:
      x-bin from [x_min, x_max] into 4 bins
      v-bin from [v_min, v_max] into 4 bins
      symbol = 4 * x_bin + v_bin
    """
    x_min, x_max = float(xs.min()), float(xs.max())
    v_min, v_max = float(vs.min()), float(vs.max())

    # Guard against degenerate ranges
    if x_max <= x_min:
        x_max = x_min + 1e-6
    if v_max <= v_min:
        v_max = v_min + 1e-6

    x_norm = (xs - x_min) / (x_max - x_min + 1e-12)   # ideally in [0, 1]
    v_norm = (vs - v_min) / (v_max - v_min + 1e-12)

    # Map to 4 bins via floor
    x_bin = np.floor(4.0 * x_norm).astype(np.int64)
    v_bin = np.floor(4.0 * v_norm).astype(np.int64)

    # Right endpoint lands at 4 due to floating arithmetic; clip back to 3
    x_bin = np.clip(x_bin, 0, 3)
    v_bin = np.clip(v_bin, 0, 3)

    symbols = 4 * x_bin + v_bin
    return symbols.astype(np.int64)


def continuous_observation(xs: np.ndarray, vs: np.ndarray, W_cont: np.ndarray) -> np.ndarray:
    """
    Returns shape (T, 16)
    """
    z = np.stack([xs, vs], axis=-1).astype(np.float32)   # (T, 2)
    return z @ W_cont                                    # (T, 16)


def discrete_observation(symbols: np.ndarray, codebook: np.ndarray) -> np.ndarray:
    """
    codebook: (16, 16), columns are the code vectors.
    symbols: (T,)
    returns: (T, 16)
    """
    return codebook[:, symbols].T.astype(np.float32)


def build_observation(xs: np.ndarray, vs: np.ndarray, eta: float, W_cont: np.ndarray, codebook: np.ndarray):
    """
    Returns:
      obs: (T, 16)
      symbols: (T,)
    """
    symbols = quantize_per_trajectory(xs, vs)
    cont = continuous_observation(xs, vs, W_cont)
    disc = discrete_observation(symbols, codebook)
    obs = (1.0 - eta) * cont + eta * disc
    return obs.astype(np.float32), symbols


def simulate_one_example(
    mu: float,
    L: int,
    horizon: int,
    dt: float,
    x0: float,
    v0: float,
    eta: float,
    W_cont: np.ndarray,
    codebook: np.ndarray,
    burn_in: int = 0,
):
    total_len = L + horizon
    xs, vs = simulate_vdp(mu=mu, total_len=total_len, dt=dt, x0=x0, v0=v0, burn_in=burn_in)
    obs, symbols = build_observation(xs, vs, eta=eta, W_cont=W_cont, codebook=codebook)

    x_in = obs[:L]                  # (L, 16)
    y_out = obs[L:L + horizon]      # (H, 16)

    return x_in, y_out, symbols


def make_split(
    n: int,
    split_name: str,
    L: int,
    horizon: int,
    dt: float,
    eta: float,
    mu_min: float,
    mu_max: float,
    x0_range,
    v0_range,
    burn_in: int,
    seed: int,
    W_cont: np.ndarray,
    codebook: np.ndarray,
):
    rng = np.random.default_rng(seed)

    mus = rng.uniform(mu_min, mu_max, size=n).astype(np.float32)
    x0s = rng.uniform(x0_range[0], x0_range[1], size=n).astype(np.float32)
    v0s = rng.uniform(v0_range[0], v0_range[1], size=n).astype(np.float32)

    X = np.empty((n, L, 16), dtype=np.float32)
    Y = np.empty((n, horizon, 16), dtype=np.float32)

    unique_symbol_counts = []

    for i in progress(range(n), total=n, desc=f"Generating {split_name}", unit="traj"):
        x_in, y_out, symbols = simulate_one_example(
            mu=float(mus[i]),
            L=L,
            horizon=horizon,
            dt=dt,
            x0=float(x0s[i]),
            v0=float(v0s[i]),
            eta=float(eta),
            W_cont=W_cont,
            codebook=codebook,
            burn_in=burn_in,
        )

        X[i] = x_in
        Y[i] = y_out

        unique_symbol_counts.append(int(np.unique(symbols[:L]).size))

        # Light debugging for first few examples
        if i < 3:
            print(f"[{split_name} sample {i}] unique symbols in input = {np.unique(symbols[:L]).size}")
            print(f"[{split_name} sample {i}] first 24 symbols = {symbols[::24].tolist()}")
            print(f"[{split_name} sample {i}] unique 16D vectors in input = {np.unique(x_in, axis=0).shape[0]}")

    stats = {
        "avg_unique_symbols": float(np.mean(unique_symbol_counts)),
        "min_unique_symbols": int(np.min(unique_symbol_counts)),
        "max_unique_symbols": int(np.max(unique_symbol_counts)),
    }
    
    if horizon == 1:
        Y = Y[:, 0, :]

    return X, Y, stats


def main():
    p = argparse.ArgumentParser()

    p.add_argument("--out", type=str, required=True)

    p.add_argument("--L", type=int, default=1024)
    p.add_argument("--horizon", type=int, default=16)
    p.add_argument("--delta", type=float, default=0.01)
    p.add_argument("--eta", type=float, default=1.0)

    p.add_argument("--d_input", type=int, default=16)

    p.add_argument("--n_train", type=int, default=20000)
    p.add_argument("--n_val", type=int, default=2000)
    p.add_argument("--n_test", type=int, default=2000)

    p.add_argument("--mu_min", type=float, default=0.1)
    p.add_argument("--mu_max", type=float, default=5.0)

    p.add_argument("--x0_range", type=float, nargs=2, default=(-2.0, 2.0))
    p.add_argument("--v0_range", type=float, nargs=2, default=(-2.0, 2.0))

    p.add_argument("--burn_in", type=int, default=0)

    p.add_argument("--seed", type=int, default=37)
    args = p.parse_args()

    if args.d_input != 16:
        raise ValueError("This script is written for d_input=16 exactly.")
    if not (0.0 <= args.eta <= 1.0):
        raise ValueError("--eta must lie in [0, 1].")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    W_cont = build_continuous_map(d_input=args.d_input, seed=args.seed + 101)
    codebook = build_orthogonal_codebook(d_input=args.d_input, seed=args.seed + 202)

    x_train, y_train, train_stats = make_split(
        n=args.n_train,
        split_name="train",
        L=args.L,
        horizon=args.horizon,
        dt=args.delta,
        eta=args.eta,
        mu_min=args.mu_min,
        mu_max=args.mu_max,
        x0_range=args.x0_range,
        v0_range=args.v0_range,
        burn_in=args.burn_in,
        seed=args.seed + 0,
        W_cont=W_cont,
        codebook=codebook,
    )

    x_val, y_val, val_stats = make_split(
        n=args.n_val,
        split_name="val",
        L=args.L,
        horizon=args.horizon,
        dt=args.delta,
        eta=args.eta,
        mu_min=args.mu_min,
        mu_max=args.mu_max,
        x0_range=args.x0_range,
        v0_range=args.v0_range,
        burn_in=args.burn_in,
        seed=args.seed + 1,
        W_cont=W_cont,
        codebook=codebook,
    )

    x_test, y_test, test_stats = make_split(
        n=args.n_test,
        split_name="test",
        L=args.L,
        horizon=args.horizon,
        dt=args.delta,
        eta=args.eta,
        mu_min=args.mu_min,
        mu_max=args.mu_max,
        x0_range=args.x0_range,
        v0_range=args.v0_range,
        burn_in=args.burn_in,
        seed=args.seed + 2,
        W_cont=W_cont,
        codebook=codebook,
    )

    meta = {
        "system": "van_der_pol",
        "task": "forecast_future_mixed_observation",
        "L": int(args.L),
        "horizon": int(args.horizon),
        "delta": float(args.delta),
        "eta": float(args.eta),
        "d_input": int(args.d_input),
        "mu_min": float(args.mu_min),
        "mu_max": float(args.mu_max),
        "x0_range": [float(args.x0_range[0]), float(args.x0_range[1])],
        "v0_range": [float(args.v0_range[0]), float(args.v0_range[1])],
        "burn_in": int(args.burn_in),
        "binning": "per_trajectory_4x4_on_[xmin,xmax]x[vmin,vmax]",
        "codebook": "global_random_orthogonal_16x16_columns",
        "train_symbol_stats": train_stats,
        "val_symbol_stats": val_stats,
        "test_symbol_stats": test_stats,
        "seed": int(args.seed),
    }

    np.savez_compressed(
        out_path,
        x_train=x_train,
        y_train=y_train,
        x_val=x_val,
        y_val=y_val,
        x_test=x_test,
        y_test=y_test,
        W_cont=W_cont,
        codebook=codebook,
        meta_json=json.dumps(meta),
    )

    print(f"Saved: {out_path}")
    print(f"x_train {x_train.shape}, y_train {y_train.shape}")
    print(f"train avg unique symbols: {train_stats['avg_unique_symbols']:.2f}")
    print(f"train min/max unique symbols: {train_stats['min_unique_symbols']} / {train_stats['max_unique_symbols']}")


if __name__ == "__main__":
    main()